# Generated by Django 4.1 on 2024-09-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("adult", models.BooleanField(default=False)),
                ("original_language", models.CharField(max_length=10)),
                ("original_title", models.CharField(max_length=255)),
                ("genre_ids", models.JSONField()),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("popularity", models.FloatField()),
                ("vote_count", models.IntegerField()),
                ("video", models.BooleanField(default=False)),
                ("vote_average", models.FloatField()),
            ],
        ),
    ]
