# Generated by Django 4.1 on 2024-09-04 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0002_auto_populate_data"),
    ]

    operations = []
