# Generated by Django 5.1.1 on 2024-09-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiShotServer', '0004_auto_20240904_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='AiShotServer.movie')),
            ],
        ),
    ]
