# Generated by Django 4.1 on 2024-09-20

from django.db import migrations

def load_initial_data(apps, schema_editor):
    Movie = apps.get_model('AiShotServer', 'Movie')
    Video = apps.get_model('AiShotServer', 'Video')

    # 创建电影数据
    #movie = Movie.objects.create(id=123,genre_ids="1,2,3")
    # 查询 ID 为 123 的电影
    try:
        movie = Movie.objects.get(id=1)
    except Movie.DoesNotExist:
    # 如果没有找到对应的电影，则抛出错误或处理逻辑
        print("Movie with id 1 does not exist.")
        return
    
    
    
    
    videos = [
        {
            "video_id": "123",
            "name": "Trailer 1",
            "site": "https://www.bilibili.com/video/905833761.mp4?t=5.6",
            "key": "Xyz123",
            "size": 720,
            "type": "Trailer"
        },
        {
            "video_id": "124",
            "name": "Clip 1",
            "site": "https://www.bilibili.com/video/905833761.mp4?t=5.6",
            "key": "Xyz124",
            "size": 1080,
            "type": "Clip"
        },
         {
            "video_id": "12",
            "name": "Trailer 1",
            "site": "https://www.bilibili.com/video/905833761.mp4?t=5.6",
            "key": "Xyz123",
            "size": 720,
            "type": "Trailer"
        },
        {
            "video_id": "14",
            "name": "Clip 1",
            "site": "https://www.bilibili.com/video/905833761.mp4?t=5.6",
            "key": "Xyz124",
            "size": 1080,
            "type": "Clip"
        },
         {
            "video_id": "13",
            "name": "Trailer 1",
            "site": "https://www.bilibili.com/video/905833761.mp4?t=5.6",
            "key": "Xyz123",
            "size": 720,
            "type": "Trailer"
        },
        {
            "video_id": "11",
            "name": "Clip 1",
            "site": "https://www.bilibili.com/video/905833761.mp4?t=5.6",
            "key": "Xyz124",
            "size": 1080,
            "type": "Clip"
        }
    ]

    for video_data in videos:
        print(f"Adding video: {video_data['video_id']}")
        Video.objects.create(
            movie=movie,
            video_id=video_data['video_id'],
            name=video_data['name'],
            site=video_data['site'],
            key=video_data['key'],
            size=video_data['size'],
            type=video_data['type']
        )

class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0006_video_id"),

    ]
    operations = [
        migrations.RunPython(load_initial_data),
    ]
