# Generated by Django 5.1.1 on 2024-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiShotServer', '0007_auto_20241002_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.CharField(default='daixf', max_length=255),
            preserve_default=False,
        ),
    ]
