# Generated by Django 5.1.1 on 2024-10-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0011_alter_movie_adult_alter_movie_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="site",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="type",
            field=models.CharField(blank=True, default="image", max_length=255),
        ),
    ]
