# Generated by Django 5.1.1 on 2024-10-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0013_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ShotConfig",
            fields=[
                ("configUI_id", models.IntegerField(primary_key=True, serialize=False)),
                ("radius_mm", models.FloatField()),
                ("thinofrubber_mm", models.FloatField()),
                ("initlengthofrubber_m", models.FloatField()),
                ("widthofrubber_mm", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("crossofrubber", models.FloatField()),
                ("Cd", models.FloatField()),
                ("airrho", models.FloatField()),
                ("velocity", models.FloatField()),
                ("pellet", models.IntegerField()),
                ("eyeToBowDistance", models.FloatField()),
                ("eyeToAxisDistance", models.FloatField()),
                ("shotDoorWidth", models.FloatField()),
                ("shotHeadWidth", models.FloatField()),
                ("altitude", models.IntegerField()),
                ("isalreadyDown", models.IntegerField()),
            ],
        ),
    ]
