# Generated by Django 5.1.1 on 2024-10-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0014_review_shotconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("page", models.IntegerField()),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("popularity", models.FloatField()),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vote_average", models.FloatField()),
                ("overview", models.TextField()),
                ("first_air_date", models.DateField(blank=True, null=True)),
                ("origin_country", models.JSONField()),
                ("genre_ids", models.JSONField()),
                ("original_language", models.CharField(max_length=10)),
                ("vote_count", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "shop",
            },
        ),
    ]
