# Generated by Django 5.1.1 on 2024-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0015_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotconfig",
            name="configUI_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
