# Generated by Django 5.1.1 on 2024-10-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0016_alter_shotconfig_configui_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotconfig",
            name="configUI_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
