# Generated by Django 5.1.1 on 2024-10-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0019_movie_user_review_movie_uploadedfile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="defualt_avatar.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
