# Generated by Django 5.1.1 on 2024-10-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0020_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
