# Generated by Django 5.1.1 on 2024-10-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0023_product_alter_review_url_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
