# Generated by Django 5.1.1 on 2024-10-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0024_alter_product_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[("铂金版", "铂金版"), ("黄金版", "黄金版"), ("白银版", "白银版")],
                        default="铂金版",
                        max_length=20,
                    ),
                ),
                ("bow_gate_distance", models.FloatField(default=0.04)),
                ("head_width", models.FloatField(default=0.025)),
                ("rubber_thickness", models.FloatField(default=0.0045)),
                ("initial_rubber_length", models.FloatField(default=0.22)),
                ("rubber_width", models.FloatField(default=0.025)),
                (
                    "wifi_account",
                    models.CharField(default="aishotclient", max_length=100),
                ),
                (
                    "wifi_password",
                    models.CharField(default="aishotclient123", max_length=100),
                ),
                ("ble_connection", models.BooleanField(default=False)),
                ("battery_level", models.IntegerField(default=100)),
            ],
        ),
    ]
