# Generated by Django 5.1.1 on 2024-10-12 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0025_deviceprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shotconfig",
            old_name="velocity",
            new_name="initvelocity",
        ),
    ]
