# Generated by Django 5.1.1 on 2024-10-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0026_rename_velocity_shotconfig_initvelocity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceprofile",
            name="initial_rubber_length",
            field=models.FloatField(
                choices=[
                    ("0.18", "0.18"),
                    ("0.19", "0.19"),
                    ("0.20", "0.20"),
                    ("0.21", "0.21"),
                    ("0.22", "0.22"),
                    ("0.23", "0.23"),
                    ("0.24", "0.24"),
                    ("0.25", "0.25"),
                ],
                default=0.22,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deviceprofile",
            name="rubber_thickness",
            field=models.FloatField(
                choices=[
                    ("0.0045", "0.0045"),
                    ("0.0050", "0.0050"),
                    ("0.0055", "0.0055"),
                    ("0.0060", "0.0060"),
                    ("0.0065", "0.0065"),
                    ("0.0070", "0.0070"),
                    ("0.0075", "0.0075"),
                    ("0.0080", "0.0080"),
                    ("0.0085", "0.0085"),
                    ("0.0090", "0.0090"),
                    ("0.0095", "0.0095"),
                    ("0.0100", "0.0100"),
                ],
                default=0.0045,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deviceprofile",
            name="rubber_width",
            field=models.FloatField(
                choices=[
                    ("0.18", "0.18"),
                    ("0.20", "0.20"),
                    ("0.25", "0.25"),
                    ("0.30", "0.30"),
                ],
                default=0.025,
                max_length=20,
            ),
        ),
    ]
