# Generated by Django 5.1.1 on 2024-10-14 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0027_alter_deviceprofile_initial_rubber_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceprofile",
            name="initial_rubber_length",
        ),
        migrations.RemoveField(
            model_name="deviceprofile",
            name="rubber_thickness",
        ),
        migrations.RemoveField(
            model_name="deviceprofile",
            name="rubber_width",
        ),
        migrations.AddField(
            model_name="deviceprofile",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="InitialRubberLength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("0.18", "0.18"),
                            ("0.19", "0.19"),
                            ("0.20", "0.20"),
                            ("0.21", "0.21"),
                            ("0.22", "0.22"),
                            ("0.23", "0.23"),
                            ("0.24", "0.24"),
                            ("0.25", "0.25"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "device_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_rubber_lengths",
                        to="AiShotServer.deviceprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RubberThickness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thickness",
                    models.CharField(
                        choices=[
                            ("0.0045", "0.0045"),
                            ("0.0050", "0.0050"),
                            ("0.0055", "0.0055"),
                            ("0.0060", "0.0060"),
                            ("0.0065", "0.0065"),
                            ("0.0070", "0.0070"),
                            ("0.0075", "0.0075"),
                            ("0.0080", "0.0080"),
                            ("0.0085", "0.0085"),
                            ("0.0090", "0.0090"),
                            ("0.0095", "0.0095"),
                            ("0.0100", "0.0100"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "device_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubber_thicknesses",
                        to="AiShotServer.deviceprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RubberWidth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        choices=[
                            ("0.18", "0.18"),
                            ("0.20", "0.20"),
                            ("0.25", "0.25"),
                            ("0.30", "0.30"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "device_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubber_widths",
                        to="AiShotServer.deviceprofile",
                    ),
                ),
            ],
        ),
    ]
