# Generated by Django 5.1.1 on 2024-10-14 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0028_remove_deviceprofile_initial_rubber_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceprofile",
            name="initial_rubber_length",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AiShotServer.initialrubberlength",
            ),
        ),
        migrations.AddField(
            model_name="deviceprofile",
            name="rubber_thickness",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AiShotServer.rubberthickness",
            ),
        ),
        migrations.AddField(
            model_name="deviceprofile",
            name="rubber_width",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AiShotServer.rubberwidth",
            ),
        ),
        migrations.CreateModel(
            name="RubberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rubber_thickness", models.FloatField(default=0.0045)),
                ("initial_rubber_length", models.FloatField(default=0.22)),
                ("rubber_width", models.FloatField(default=0.025)),
                (
                    "device_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubber_profiles",
                        to="AiShotServer.deviceprofile",
                    ),
                ),
            ],
        ),
    ]
