# Generated by Django 5.1.1 on 2024-10-14 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiShotServer", "0029_deviceprofile_initial_rubber_length_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deviceprofile",
            old_name="initial_rubber_length",
            new_name="initlengthofrubber_m",
        ),
        migrations.RenameField(
            model_name="deviceprofile",
            old_name="bow_gate_distance",
            new_name="shotDoorWidth",
        ),
        migrations.RenameField(
            model_name="deviceprofile",
            old_name="head_width",
            new_name="shotHeadWidth",
        ),
        migrations.RenameField(
            model_name="deviceprofile",
            old_name="rubber_thickness",
            new_name="thinofrubber_mm",
        ),
        migrations.RenameField(
            model_name="deviceprofile",
            old_name="rubber_width",
            new_name="widthofrubber_mm",
        ),
        migrations.RemoveField(
            model_name="shotconfig",
            name="initlengthofrubber_m",
        ),
        migrations.RemoveField(
            model_name="shotconfig",
            name="shotDoorWidth",
        ),
        migrations.RemoveField(
            model_name="shotconfig",
            name="shotHeadWidth",
        ),
        migrations.RemoveField(
            model_name="shotconfig",
            name="thinofrubber_mm",
        ),
        migrations.RemoveField(
            model_name="shotconfig",
            name="widthofrubber_mm",
        ),
        migrations.AddField(
            model_name="shotconfig",
            name="device_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shot_configs",
                to="AiShotServer.deviceprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="initialrubberlength",
            name="length",
            field=models.CharField(
                choices=[
                    ("180", "180"),
                    ("190", "190"),
                    ("200", "200"),
                    ("210", "210"),
                    ("220", "220"),
                    ("230", "230"),
                    ("240", "240"),
                    ("250", "250"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rubberthickness",
            name="thickness",
            field=models.CharField(
                choices=[
                    ("0.45", "0.45"),
                    ("0.50", "0.50"),
                    ("0.55", "0.55"),
                    ("0.60", "0.60"),
                    ("0.65", "0.65"),
                    ("0.70", "0.70"),
                    ("0.75", "0.75"),
                    ("0.80", "0.80"),
                    ("0.85", "0.85"),
                    ("0.90", "0.90"),
                    ("0.95", "0.95"),
                    ("1", "1"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rubberwidth",
            name="width",
            field=models.CharField(
                choices=[("18", "18"), ("20", "20"), ("25", "25"), ("30", "30")],
                max_length=10,
            ),
        ),
    ]
