# Generated by Django 5.1.1 on 2024-10-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "AiShotServer",
            "0030_rename_initial_rubber_length_deviceprofile_initlengthofrubber_m_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="initialrubberlength",
            name="length",
            field=models.CharField(
                choices=[
                    ("0.18", "0.18"),
                    ("0.19", "0.19"),
                    ("0.20", "0.20"),
                    ("0.21", "0.21"),
                    ("0.22", "0.22"),
                    ("0.23", "0.23"),
                    ("0.24", "0.24"),
                    ("0.25", "0.25"),
                ],
                max_length=10,
            ),
        ),
    ]
